### ISSUE TITLE
Can't login with Google

### ISSUE THREAD

**Issue by bicheichane** [alexfruehwirth/franz-asana#1]
When pressing "Use Google Account" it opens a new tab on my default browser, Chrome, and although it appears to have a meaningful link, the page stays blank and doesn't actually let me try to log in with a google account!

**Comment by alexfruehwirth** [comment]
Hi,
uh. Never used it with the google login.
I'll have a look into and get back to you as soon as i've found a solution 😃

**Comment by JehutyPT** [comment]
Thanks a lot! :D

2016-11-30 10:01 GMT+00:00 Alexander Frühwirth <notifications@github.com>:

**Comment by gtweigel** [comment]
any updates here? would love to be able to attach files via google drive!

**Comment by juniors15** [comment]
any update?

**Comment by alexfruehwirth** [comment]
I had a look into it. It's more a problem of Franz/Electron not opening the oauth link correctly. 
There is not really a way for plugin authors to bypass this. I'm afraid this can't be fixed :(
